version: '3.1'

services:
  front:
    build:
      context: ./front/
    ports:
      - "4200:4200"
    volumes:
      - ./front/:/app/front
    depends_on:
      - back
  back:
    build:
      context: ./back/
    ports:
      - "8080:8080"
    volumes:
      - ./back/:/app/back
